import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className="h-full antialiased">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.3.1/css/all.min.css"
          integrity="sha512-QeR2VH+lsBE5LSAe1Q5EnTBbe7XTBubt8dG93Y7gidSgdMCr8nVqKcfKAMyN96SV8KDbZVTDXChatu5G2KQGzg=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
          precedence="default"></link>
      </head>

      <body className="min-h-full flex flex-col">
        {children}
        <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
      </body>
    </html>
  );
}
